# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minnesboken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_featured_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
